language: node_js
node_js:
- 12.19.0
branches:
  only:
  - master
install:
- npm config set registry https://registry.npm.taobao.org
- npm install
scripts:
- npm run build
addons:
  ssh_known_hosts: 47.98.183.206
  apt:
    packages:
    - sshpass
after_success:
- chmod 600 ~/.ssh/id_rsa
- export SSHPASS=$DEPLOY_PASS
- sshpass -e ssh -o stricthostkeychecking=no root@47.98.183.206 "cd /eric/personal-web/personal-web-client
  && git pull origin master && sh ./deploy.sh"
env:
  global:
  - secure: EU5cm/yvJw3OuR/IaQQsyMpjU67EzHIvBwpwgtEcHMdh1A5oLfz82TTr4s9xZeReNrfwIwqaowh10LrD6EjdbEmQ0YQFcZuNkbYbnVpBYm0Cr5/j9QNv2704rtz5XzWNFCZVfLzf7ql8o0Gkt2A7qAsxe4100FK7P0nx+9BoUBIfKyA94qG2s0gjsh4wa1JrnqrzskebE1HpsTs6i/eUChLQ58tnFWkesc/rbTlI/TQqaMnRWkEyXxZMi+XUgYWWXZCMs/CbJWSvSaytz8O2r+Y+F0yPN0x6gEK33yGPHi6pjZervWQoidO2IH1R9eBr4XTY6XHsXg48SQBt/olgFA0ATRqDZ1MwzPk7cdTLruht+JKKRSbLPOPbpi2Rz0gHP77dFuPw+3weclJyrVXKd9lXhKP938RmSeJ92AUl/+rZ2FkOm3dOLqg5pg+Ztsu9RQKcQMQxs1djivgkzRNhKwuKNBda8ukh+ReTD3e8ASfWHCEfu1KnoY5vD6PCRxz1RJ/b9eiT+mjl2af6HcgpAj9AJ6iJJHYX+TEGJTatFPYvfSRkI4S4V84BOT/7qZCwdOT77woFDc+9A5eYlaA/95exNNQLFzpd07NI5QaYDfE3tTegomhNQPSPSqcY3HWU72kcxzceXOIX4WLrgET2QpAB622iXKbZNAyG72rJt1Y=
