version: '3'

networks:
  my-network:
    driver: bridge

services:
  ### client ########################
  client:
    container_name: client
    build: .
    ports:
      - 5000:5000
    restart: always
    networks:
      - my-network
